# Generated by Django 5.1.15 on 2026-05-18 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("driver_name", models.CharField(max_length=120)),
                ("tractor_number", models.CharField(max_length=20)),
                ("trailer_number", models.CharField(max_length=20)),
                ("shipper", models.CharField(max_length=120)),
                ("commodity", models.CharField(max_length=120)),
                (
                    "total_off_duty_hrs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "total_sleeper_hrs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "total_driving_hrs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "total_on_duty_hrs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "total_miles",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "total_on_clock_hrs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
            ],
            options={
                "ordering": ["trip_id", "date"],
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_location", models.CharField(max_length=200)),
                ("pickup_location", models.CharField(max_length=200)),
                ("dropoff_location", models.CharField(max_length=200)),
                (
                    "current_cycle_used_hrs",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total_miles",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "total_drive_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_legal", models.BooleanField(blank=True, null=True)),
                (
                    "cycle_used_at_end",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "not_legal_reason",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("route_geometry", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time_minutes", models.IntegerField()),
                ("end_time_minutes", models.IntegerField()),
                (
                    "duty_status",
                    models.IntegerField(
                        choices=[
                            (1, "Off-Duty"),
                            (2, "Sleeper Berth"),
                            (3, "Driving"),
                            (4, "On-Duty (not driving)"),
                        ]
                    ),
                ),
                ("city", models.CharField(max_length=120)),
                ("state", models.CharField(max_length=2)),
                ("remark", models.CharField(blank=True, default="", max_length=200)),
                ("is_stationary", models.BooleanField(default=False)),
                (
                    "log_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="trips.logday",
                    ),
                ),
            ],
            options={
                "ordering": ["log_day_id", "start_time_minutes"],
            },
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PICKUP", "Pickup"),
                            ("DROPOFF", "Dropoff"),
                            ("FUEL", "Fuel"),
                            ("REST_10", "10-hour rest"),
                            ("BREAK_30", "30-minute break"),
                        ],
                        max_length=10,
                    ),
                ),
                ("city", models.CharField(max_length=120)),
                ("state", models.CharField(max_length=2)),
                ("lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("mile_marker", models.DecimalField(decimal_places=2, max_digits=8)),
                ("arrive_at", models.DateTimeField()),
                ("depart_at", models.DateTimeField()),
                ("duration_minutes", models.IntegerField()),
                ("remark", models.CharField(blank=True, default="", max_length=200)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["trip_id", "arrive_at"],
            },
        ),
        migrations.AddField(
            model_name="logday",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="log_days",
                to="trips.trip",
            ),
        ),
        migrations.AddConstraint(
            model_name="logday",
            constraint=models.UniqueConstraint(
                fields=("trip", "date"), name="unique_logday_per_trip_date"
            ),
        ),
    ]
