# Generated by Django 5.1.15 on 2026-05-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stop",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEADHEAD", "Deadhead depart"),
                    ("PICKUP", "Pickup"),
                    ("DROPOFF", "Dropoff"),
                    ("FUEL", "Fuel"),
                    ("REST_10", "10-hour rest"),
                    ("BREAK_30", "30-minute break"),
                ],
                max_length=10,
            ),
        ),
    ]
